CRD/Controllers/JobSearchController.cs
using CRD.Core;
using CRD.Core.Attributes;
using CRD.Core.Models;
using CRD.Core.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CRD.Controllers
{
    [CustomAuthorize(Roles = "JobSeeker")]
    public class JobSearchController : BaseController
    {

        public JobSearchController(
            IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        [HttpGet]
        [Route("jobseeker/positions/search")]
        public ActionResult Search()
        {
            return Search(new JobSearchViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("jobseeker/positions/search")]
        public ActionResult Search(JobSearchViewModel model)
        {
            var jobSeeker = Session["User"] as JobSeekerAccount;
            if (jobSeeker == null)
                return RedirectToLoginPage;

            var jobPositionExcepts = UnitOfWork.JobApplications.GetAppliedJobPositionsIds(jobSeeker.Id);

            var jobPositionsViewModel = new List<JobPositionViewModel>();

            var searchTerm = model.SearchTerm;
            var includeEmployers = model.IncludeEmployers;
            var includeRecruitmentAgencies = model.IncludeRecruitmentAgencies;
            var maxElementsToRetrieve = model.MaxElementsToRetrieve;

            if (includeEmployers)
            {
                var employerJobPositions = UnitOfWork.JobSearches
                    .SearchByEmployers(maxElementsToRetrieve, searchTerm)
                    .Where(j => !jobPositionExcepts.Contains(j.Id));

                var employerJobPositionViewModel = employerJobPositions
                    .Select(j => new EmployerJobPositionViewModel()
                    {
                        Id = j.Id,
                        CompanyName = j.Employer.CompanyName,
                        JobTitle = j.JobTitle,
                        JobDescription = j.JobDescription,
                        PostedDate = j.PostedDate.ToString("dd.MM.yyyy"),
                        ExpiryDate = j.ExpiryDate.ToString("dd.MM.yyyy")
                    });

                jobPositionsViewModel.AddRange(employerJobPositionViewModel);
            }

            if (jobPositionsViewModel.Count < maxElementsToRetrieve)
            {
                if (includeRecruitmentAgencies)
                {
                    var nElementsLeftToRetrieve = maxElementsToRetrieve - jobPositionsViewModel.Count;

                    var recruitmentAgencyJobPositions = UnitOfWork.JobSearches
                        .SearchByRecruiters(nElementsLeftToRetrieve, searchTerm)
                        .Where(j => !jobPositionExcepts.Contains(j.Id));

                    var recruitmentAgencyJobPositionViewModel = recruitmentAgencyJobPositions
                        .Select(j => new RecruitmentAgencyJobPositionViewModel()
                        {
                            Id = j.Id,
                            CompanyName = j.RecruitmentAgency.CompanyName,
                            JobTitle = j.JobTitle,
                            JobDescription = j.JobDescription,
                            PostedDate = j.PostedDate.ToString("dd.MM.yyyy"),
                            ExpiryDate = j.ExpiryDate.ToString("dd.MM.yyyy")
                        });
                    jobPositionsViewModel.AddRange(recruitmentAgencyJobPositionViewModel);
                }
            }

            var viewModel = model;
            viewModel.JobPositions = jobPositionsViewModel;

            return View("Listing", viewModel);
        }
    }
}

CRD/Views/Shared/_Layout.cshtml
@{
    var isAuthenticated = User.Identity.IsAuthenticated;
    var userRole = HttpContext.Current.Session["UserRole"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (!isAuthenticated)
                {
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    switch (userRole)
                    {
                        case "JobSeeker":
                            @Html.ActionLink("Job Seeker", "Index", "JobSeekerAccount", new { area = "" }, new { @class = "navbar-brand" });
                            break;
                        case "Employer":
                            @Html.ActionLink("Employer", "Index", "EmployerAccount", new { area = "" }, new { @class = "navbar-brand" });
                            break;
                        case "RecruitmentAgency":
                            @Html.ActionLink("Recruiter", "Index", "RecruitmentAgencyAccount", new { area = "" }, new { @class = "navbar-brand" });
                            break;
                        default:
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });
                            break;
                    }
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!isAuthenticated)
                    {
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    }
                    else
                    {
                        switch (userRole)
                        {
                            case "JobSeeker":
                                <li>@Html.ActionLink("Applications", "Index", "JobApplication")</li>
                                <li>@Html.ActionLink("Educations", "Index", "JobSeekerEducation")</li>
                                <li>@Html.ActionLink("Experiences", "Index", "JobSeekerExperience")</li>
                                    <li>@Html.ActionLink("Courses", "Index", "JobSeekerCourse")</li>
                                    <li>@Html.ActionLink("Find Jobs", "Search", "JobSearch")</li>
                                    <li>@Html.ActionLink("Settings", "Edit", "JobSeekerAccount")</li>
                                break;
                            case "Employer":
                                <li>@Html.ActionLink("Positions", "Index", "EmployerJobPosition")</li>
                                <li>@Html.ActionLink("Contacts", "Index", "EmployerContactPerson")</li>
                                    <li>@Html.ActionLink("Recruiters", "Recruiters", "EmployerAccount")</li>
                                break;
                            case "RecruitmentAgency":
                                <li>@Html.ActionLink("Positions", "Index", "RecruitmentAgencyJobPosition")</li>
                                <li>@Html.ActionLink("Contacts", "Index", "RecruitmentAgencyContactPerson")</li>
                                    <li>@Html.ActionLink("Employers", "Employers", "RecruitmentAgencyAccount")</li>
                                break;
                            default:
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                break;
                        }
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>